# -----------        General Stuff        -----------
# Available: FlatFile / MySQL
# We highly recommend to use FlatFile. Please consider your use case.
DatabaseType: FlatFile
MySQL:
  Hostname: localhost
  Port: 3306
  Database: minecraft
  User: root
  Password: passy

# You can define a list of worlds, in which landlord should be disabled
# You can use Regex in order to match multiple worlds at the time.
# https://regexr.com/
# world_.* matches all worlds that start with "world_"
disabled-worlds:
  - world_nether
  - world_the_end

language: en

# amount of entries per page in the help menu
HelpCommandPerSite: 10

# Disables the warning for invalid world names on startup. Be careful!
DisableStartupWorldWarning: false

# -----------        Cost Stuff        ------------
# this formula uses limited growth. Cost will raise and raise until it reaches a certain point
# you can play around with the formula here: https://www.geogebra.org/m/S6uSGV7c
Economy:
  enable: true
  # This option overrides worldBalance, only use it if you have a different currency for each world.
  playerWorldBased: false
  # Only change this value if you need a specific world balance for Landlord's transactions, it applies in every world.
  worldBalance: 'default'

# Available are: LINEAR, EXPONENTIAL, LOGARITHMIC, SINUS, LIMITED
Growth:
  function: LIMITED
  # x is the amount of owned lands!
  # Formula: minCost + multiplier * x
  LINEAR:
    minCost: 500.0
    multiplier: 1.0
  # Formula: minCost + multiplier * x ^ exponent
  EXPONENTIAL:
    minCost: 500.0
    multiplier: 1.0
    exponent: 2.0
  # Formula: minCost + multiplier * lg (b * x + c)
  LOGARITHMIC:
    minCost: 500.0
    multiplier: 1.0
    b: 1.0
    c: 1
  # Formula: minCost + multiplier * sin (b * x + c)
  SINUS:
    minCost: 500.0
    multiplier: 3.0
    b: 1.0
    c: 1.0
  # Formula: maxCost - ( maxCost - minCost ) * multiplier ^ x
  LIMITED:
    maxCost: 3000.0
    minCost: 500.0
    multiplier: 0.95

# on unclaim, this percentage of the original price is paid back.
Payback: 0.8
# amount of free lands every user got before he has to pay
Freelands: 1
# cost for regenerate inside ll manage
ResetCost: 1000.0

Regeneration:
  # Providers available: default
  # default: regenerates the chunk by using the original seed.
  provider: 'default'

# here you can manage your claims shop.
Claims:
  # set this to false, if you want to use the traditional permission based system
  # if this is true, a player will still need the limit permissions to be able to buy claims.
  enable: true
  # amount of free claims a user should be able to receive for free.
  free: 1
  calc:
    function: LIMITED
    # x is the amount of owned claims (/ll claims)!
    # Formula: minCost + multiplier * x
    LINEAR:
      minCost: 500.0
      multiplier: 1.0
    # Formula: minCost + multiplier * x ^ exponent
    EXPONENTIAL:
      minCost: 500.0
      multiplier: 1.0
      exponent: 2.0
    # Formula: minCost + multiplier * lg (b * x + c)
    LOGARITHMIC:
      minCost: 500.0
      multiplier: 1.0
      b: 1.0
      c: 1
    # Formula: minCost + multiplier * sin (b * x + c)
    SINUS:
      minCost: 500.0
      multiplier: 3.0
      b: 1.0
      c: 1.0
    # Formula: maxCost - ( maxCost - minCost ) * multiplier ^ x
    LIMITED:
      maxCost: 3000.0
      minCost: 500.0
      multiplier: 0.95

locationFormat: '%world% - (%x%|%z%)'
# These are hard caps. If a player has the permission "landlord.limit.10" he will be able to buy up to 10 lands.
# define all the landlord.limit.x permissions you wanna use here in this list.
# Please sort the entries ascending!

# Secures the world in which landlord is active. This means, players wont be able to destroy anything in free lands
SecureWorld:
  enable: true
  # Put here world names you want to be affected by the secure system. Leave empty for all.
  worlds:
    - world_nether
    - world_the_end
  # If player reach this treshold (amount of ownedlands) they will be able to build in the normal world)
  # This way you can allow your veteran players to be able to build pathes and commonly used stuff in the world, but prevent newbies from griefing
  threshold: 10
  perWorld: true
  # Where to display the warning that you are not to allowed in free lands until x lands has been reached: ActionBar, Chat, Title, Disabled
  displayWarning: ActionBar

Homes:
  enable: true
  # enable to this to automatically set home on claim, when the user doesnt have a previous home
  enableAutoSetHome: false
  teleportCost: 100.0
  delay: 3

# This option allows players to buy up the lands of players, who are not playing actively any longer
BuyUpInactive:
  enable: false
  # amount of days until a player is marked as "inactive" and his lands may be bought up
  timegate: 30

# Where should the "Entering XXX's land" be displayed? Available are ActionBar, Chat, Title, Disabled
LandMessage: ActionBar

ConfirmationDialog:
  # Modes: CHAT GUI
  mode: CHAT
  # Timeout for chat based confirmation. The user has x seconds time to click the chat
  timeout: 10
  onNormalClaim: true
  onBuyUp: true
  multiClaim: true
  onUnclaim: false
  onUnclaimAll: true
  onMultiUnclaim: true

# You can enable/disable the particles for particular events here
Particles:
  claim:
    enabled: true
    particle: VILLAGER_HAPPY
  unclaim:
    enabled: true
    particle: VILLAGER_ANGRY
  info:
    enabled: true
    unclaimed: DRIP_LAVA
    claimed: DRIP_WATER
    inactive: DRIP_LAVA
  borders:
    enabled: true
    unclaimed: DRIP_LAVA
    claimed: DRIP_WATER
    inactive: DRIP_LAVA

# -----------        Map Stuff        ------------
Map:
  enable: true
  # Refreshrate in Ticks. 20 ticks is equal to one second. The lower you set the value the more laggy it might be
  refreshRate: 10

Borders:
  # show the chunkborders with particles
  enable: true
  # interval in seconds
  refreshRate: 10
  # timeout value in seconds. after this amount the map will be turned off again
  timeout: 600

CommandSettings:
  Main:
    name: landlordhelp
    description: The basic command, /llhelp
    usage: 'Usage: /llhelp'
    enableMissingStringWarning: true
    permissions:
      - landlord.use
    aliases:
      - ll
      - land
      - landlord
      - gs
      - llhelp

  Claim:
    enableDelimit: true
    # set this to false, if you want the delimitation to be placed physically in the world
    enablePhantomBlocks: true
    # Newly claimed lands are delimited by this material. Example below should be self explanatory
    delimitation:
      - 'define: x=GLOWSTONE'
      - 'x--------------x'
      - '----------------'
      - '----------------'
      - '----------------'
      - '----------------'
      - '----------------'
      - '----------------'
      - '----------------'
      - '----------------'
      - '----------------'
      - '----------------'
      - '----------------'
      - '----------------'
      - '----------------'
      - '----------------'
      - 'x--------------x'
    # When a player does not own any lands, he may claim any free chunk. later only adjacent chunks
    claimOnlyAdjacent: false
    # If this is enabled, there must be one free chunk between two different owners. See https://tinyurl.com/y8xzelga
    needsGapBetweenOwners: false
    # radius
    customGapRadius: 1
    # allow to claim a land when there is already another worldguard region
    allowOverlap: false
    # if you use overlapping regions, this value manage the priority of the lands region relative to the others
    regionPriority: 0

    name: claim
    usage: 'Usage: /land claim'
    permissions:
      - landlord.player.own
    aliases:
      - buy
      - cl

  MultiClaim:
    name: multiclaim
    usage: 'Usage: /land multiclaim <mode> <radius>'
    permissions:
      - landlord.player.multiclaim
    aliases:
      - mclaim
      - mcl
      - multibuy
      - mbuy

  MultiUnclaim:
    name: multiunclaim
    usage: 'Usage: /land multiunclaim <mode> <radius>'
    permissions:
      - landlord.player.unclaim
    aliases:
      - munclaim
      - muc
      - multisell
      - ms

  MultiAddfriend:
    name: multiaddfriend
    usage: 'Usage: /land multiaddfriend <mode> <radius> <name>'
    permissions:
      - landlord.player.own
    aliases:
      - multifriendadd
      - multiaddmember
      - mfriendadd
      - maddmember

  MultiRemovefriend:
    name: multiremovefriend
    usage: 'Usage: /land multiremovefriend <mode> <radius> <name>'
    permissions:
      - landlord.player.own
    aliases:
      - multifriendremove
      - mfriendremove
      - multiunfriend
      - munfriend
      - multifrienddelete
      - mfrienddelete
      - multideletefriend
      - mdeletefriend
      - multiremovefriend
      - mremovefriend

  MultiListLands:
    name: multilist
    usage: '/land multilist <mode> <radius>'
    permissions:
      - landlord.player.own
    aliases:
      - multilistlands
      - mlistlands
      - multilandlist
      - mlandlist
    enable: true
    # gui or chat
    mode: gui
    # How many lands should be displayed per page?
    landsPerPage: 15

  MultiManage:
    name: multimanage
    usage: '/land multimanage <mode> <radius>'
    permissions:
      - landlord.player.manage
    aliases:
      - mmanage
      - multimng
      - mmng

  Info:
    name: info
    usage: '/land info - Shows information about the land you are standing on'
    permissions:
      - landlord.player.info
    aliases:
      - i

  Regenerate:
    name: regenerate
    usage: '/land regenerate - Regenerates the land you are standing on'
    permissions:
      - landlord.player.regenerate
    aliases:
      - regen

  Unclaim:
    name: unclaim
    usage: '/land unclaim - Unclaim the chunk you are standing on'
    regenerate: true
    permissions:
      - landlord.player.unclaim
    aliases:
      - sell

  UnclaimAll:
    name: unclaimall
    usage: '/land unclaimall <world> - Unclaims all your lands'
    permissions:
      - landlord.player.unclaim
    aliases:
      - sellall

  Listfriends:
    name: listfriends
    usage: '/land friends - Shows all friended players'
    permissions:
      - landlord.player.own
    aliases:
      - friends
      - fr

  Addfriend:
    name: addfriend
    usage: '/land addfriend - Adds a friend to your land'
    permissions:
      - landlord.player.own
    aliases:
      - friendadd
      - addmember

  RemoveFriend:
    name: removefriend
    usage: '/land unfriend - removes a friend from your land'
    permissions:
      - landlord.player.own
    aliases:
      - unfriend
      - friendremove
      - frienddelete
      - deletefriend
      - removefriend

  AddfriendAll:
    name: addfriendall
    usage: '/land addfriendall - Adds a friend to all of your lands'
    permissions:
      - landlord.player.own
    aliases:
      - friendaddall
      - addmemberall
      - friendall

  RemovefriendAll:
    name: removefriendall
    usage: '/land removefriendall - unfriend someone on all your lands'
    permissions:
      - landlord.player.own
    aliases:
      - unfriendall
      - removeallfriends

  ListLands:
    name: list
    usage: '/land list - lists all your lands'
    permissions:
      - landlord.player.own
    aliases:
      - listlands
      - landlist
    enable: true
    # gui or chat
    mode: gui
    # How many lands should be displayed per page?
    landsPerPage: 15

  Map:
    name: map
    usage: '/land map - toggles the landmap'
    symbols:
      background1: '▓'
      background2: '▒'
      middle: '█'
      arrow: '∞'
      yours: '█'
      friends: '█'
      others: '█'
    permissions:
      - landlord.player.map
    aliases:
      - landmap

  Clear:
    name: clear
    usage: '/land clear - clear a world'
    permissions:
      - landlord.admin.clear
    aliases:
      - clearworld

  Manage:
    name: manage
    usage: '/land manage - manages the land you are standing on'
    permissions:
      - landlord.player.manage
    aliases:
      - mgn

  ManageAll:
    name: manageall
    usage: '/land manageall - manages all your lands at the same time'
    permissions:
      - landlord.player.manage
    aliases:
      - mall

  Update:
    name: update
    usage: '<-r> - updates all lands in one world. Parameter -r forces to reset all lands to their default state'
    permissions:
      - landlord.admin.update
    aliases:
      - upd

  Shop:
    name: shop
    usage: '/land shop - displays the land shop'
    permissions:
      - landlord.player.shop
    aliases:
      - claimshop

  Reload:
    name: reload
    usage: '/land reload - THIS IS NOT RECOMMENDED!!!'
    permissions:
      - landlord.admin.reload
    aliases:
      - rl

  Claims:
    name: claims
    usage: '/land claims - shows the amount of your claims'
    permissions:
      - landlord.player.shop
    aliases:
      - clms

  Sethome:
    name: sethome
    usage: '/land sethome - sets your current land home'
    permissions:
      - landlord.player.home
    aliases:
      - homeset

  Home:
    name: home
    usage: '/land home teleports you to your home'
    permissions:
      - landlord.player.home
    aliases:
      - h

  GiveClaims:
    name: giveclaims
    usage: '/land giveclaims <amount> - give claims to yourself|/land giveclaims <name> <amount> - give claims to somebody else|/land giveclaims <name> <price> <amount> - gives claims to somebody and take money for it'
    permissions:
      - landlord.claims.give
    aliases:
      - gcl

  Advertise:
    name: advertise
    usage: '/land advertise <price> || /land advertise <landName> <price>'
    permissions:
      - landlord.player.advertise
    aliases:
      - adv

  RemoveAdvertise:
    name: removeadvertise
    usage: '/land removeadvertise'
    permissions:
      - landlord.player.advertise
    aliases:
      - remadv
      - remadvertise

  Borders:
    name: borders
    usage: '/land borders'
    permissions:
      - landlord.player.borders
    aliases:
      - toggleborders

  AdminTP:
    name: admintp
    usage: '/land admintp <name> - teleports to the land of a player'
    permissions:
      - landlord.admin.admintp
    aliases:
      - adminteleport

  AdminClaim:
    name: adminclaim
    usage: '/land adminclaim <name> - claims the land for a player'
    permissions:
      - landlord.admin.adminclaim
    aliases:
      - admincl



# define your default flags here. Every flag will be manageable in ll manage
# Construction of a new Flag:
# flag defaultState:toggleableState
# You can also set specific groups: e.g. interact allow all:deny non_members
# this allows toggling the flagstate between allowing interaction for everyone and just allow oweners and members
# if you are adding a new flag, you must implement the necessary strings in the language file! Just copy paste it from an existing flag.
Flags:
  - 'interact'
  - 'chest-access'
  - 'creeper-explosion'
  - 'pvp'
  - 'build'
  - 'damage-animals'
  - 'ride'
  - 'potion-splash'
  - 'pistons'

# These options will be manageable in ll manage
Manage:
  commands:
    Regenerate:
      enable: true
      cmd: 'll regenerate %land%'
      item: BARRIER
    Unclaim:
      enable: true
      cmd: 'll unclaim %land%'
      item: BLAZE_POWDER
  friends:
    enable: true
  setgreet:
    enable: true
    item: BAKED_POTATO
  setfarewell:
    enable: true
    item: CARROT_STICK
  damage-animals:
    enable: true
    item: RAW_FISH
    default:
      friends: true
      everyone: false
  ride:
    enable: true
    item: SADDLE
    default:
      friends: true
      everyone: false
  frosted-ice-form:
    enable: true
    item: FROSTED_ICE
    default:
      friends: true
      everyone: false
  block-trampling:
    enable: true
    item: DIAMOND_HOE
    default:
      friends: true
      everyone: false
  potion-splash:
    enable: true
    item: SPLASH_POTION
    default:
      friends: true
      everyone: false
  pistons:
    enable: true
    item: PISTON_STICKY_BASE
    default:
      friends: true
      everyone: false
  build:
    enable: true
    item: GRASS
    default:
      friends: true
      everyone: false
  interact:
    enable: true
    item: STONE_BUTTON
    default:
      friends: true
      everyone: false
  chest-access:
    enable: true
    item: CHEST
    default:
      friends: true
      everyone: false
  creeper-explosion:
    enable: true
    item: TNT
    default:
      friends: true
      everyone: false
  pvp:
    enable: true
    item: DIAMOND_SWORD
    default:
      friends: true
      everyone: false
  spread-flags:
    enable: true
    item: BOW
  spread-mobs:
    enable: true
    item: BOW
  spread-friends:
    enable: true
    item: BOW
  mob-spawning:
    enable: true
    item: MONSTER_EGG
    # If you dont want your users to manage a specific mobspawn, just comment out the line with #
    toggleableMobs:
      - ELDER_GUARDIAN
      - WITHER_SKELETON
      - STRAY
      - HUSK
      - ZOMBIE_VILLAGER
      - SKELETON_HORSE
      - ZOMBIE_HORSE
      - DONKEY
      - MULE
      - EVOKER
      - VEX
      - VINDICATOR
      - CREEPER
      - SKELETON
      - SPIDER
      - ZOMBIE
      - SLIME
      - GHAST
      - PIG_ZOMBIE
      - ENDERMAN
      - CAVE_SPIDER
      - SILVERFISH
      - BLAZE
      - MAGMA_CUBE
      - BAT
      - WITCH
      - GUARDIAN
      - GUARDIAN
      - PIG
      - SHEEP
      - COW
      - CHICKEN
      - SQUID
      - WOLF
      - OCELOT
      - HORSE
      - RABBIT
      - POLAR_BEAR
      - LLAMA
      - PARROT
      - VILLAGER

# Define how the claim height should be defined.
ClaimHeight:
  # Choose the method which should be used to define the claim Y dimensions
  # FULL - Use the full chunk from 0 to max height - 1
  # FIXED - Use the minY and maxY value as the fixed size
  # The now following methods are relativ. This means that we will substract the minY from it and add the maxY on it to define the height.
  # We use the highest block of each coordinate in the chunk. This means that we will use 16x16 blocks.
  # LOWEST - We use the lowest block in the chunk.
  # HIGHEST - We use the highest block in the chunk.
  # AVERAGE - We use the average block height of the chunk.
  # MEDIAN - We use the median of the block height in the chunk
  method: FULL
  # If you choose FULL this wont matter.
  # If you choose FIXED this will be the bottom and top y value.
  # If you use some of the relative methods this will act as an offset.
  # This also means that the values will be added on the corresponding values.
  # If you want to move the bottom down you have to insert a negative value.
  # example for relative settings:
  # bottomY: -30
  # topY: 60
  # fixed settings:
  bottomY: 0
  topY: 255
  # If you use something else than FULL or FIXED it can happen that the region would exceed the world limit.
  # If you set this to true we will add the oversize on the other end.
  # This means that if your claim would exceed the world limit on the top by 10 blocks, we add 10 blocks at the bottom of your region.
  appendOversize: false

# Sorry for the opt-out, I don't really like that. I would not opt-out for something more important. This data keeps me motivated :)
EnableMetrics: true
checkUpdatesPeriodically: true
checkUpdateOnStart: true
version: 32